### ISSUE TITLE
semver module missing

### ISSUE THREAD

**Issue by rubiojr** [risor-io/risor#260]
The `semver` built-in module documented in https://risor.io/docs/modules/semver, doesn't seem to be available.

Is that a documentation issue? I don't see it in the source tree.

**Comment by myzie** [comment]
Ah, good catch. I removed it from a branch before merging it, but the docs snuck through.

https://github.com/risor-io/risor/commit/6e46e733085dd4deda9c31e02e021299549a0d92

What gave me pause was that I wrapped `golang.org/x/mod/semver` which is fairly limited, and I realized that it's worth considering wrapping one of the more capable 3rd party libraries. But I haven't had a chance to circle back to researching which one would make the most sense.

For example there is:
- https://github.com/Masterminds/semver
- https://github.com/coreos/go-semver
- others I'm sure

For your project @rubiojr, do you have an opinion on which semver lib would be the best fit?

**Comment by rubiojr** [comment]
@myzie no strong opinions, but I'd look for the usual stuff:
* Small dependency chain
* Complete
* Well maintained
* Nice API (subjective)

The one from Masterminds would fit the bill for me.

I'd be happy to contribute that module and learn a bit more about Risor if I can get some help with the review!

**Comment by myzie** [comment]
Yeah, that would be great. After a bit more research, I think we should go with https://github.com/blang/semver unless you see a problem with it.

It's zero deps, MIT licensed, and supports ranges, comparisons, and wildcards.

You could add it as a module named `semver` in Risor. Since it has no additional deps, I'm ok with adding it to Risor core as an "always present" capability.

**Comment by rubiojr** [comment]
👍🏾 sounds great to me.
