### ISSUE TITLE
Recent changes... how to embed Risor but remove certain built-ins

### ISSUE THREAD

**Issue by edhemphill** [risor-io/risor#89]
I was wondering if you could provide some brief guidance on this issue:

Let's say we are using risor for a glue language inside of another application. There are certain built-ins we definitely do not want called - a good example being os.exit. Ideally we would pick the specific built-ins we could provide.

Recently it looks like the changes for the risor.cfg.RisorConfig struct have become an internal-only module. What then would be the best way to custom tailor the language for such a use case without forking our own version?

Thanks!

**Comment by edhemphill** [comment]
my first inclination is to just make my own version of cfg.go for our project and use it in the same way. This does not seems like a bad option.

**Comment by myzie** [comment]
Hi @edhemphill, I'll share a couple options below so let me know what you think. I'm trying to hone in on the right public API for a `v1` release. I definitely want to make sure this use case is well supported.

Regarding what you can do at this moment, I think it is possible but it might've gotten a bit more difficult depending on your exact situation. Specifically, right now you can do this:

```go
myGlobals := map[string]any{}
// Add any built-in functions or modules you want available to allowedGlobals
risor.Eval(ctx, code, risor.WithoutDefaultGlobals(), risor.WithGlobals(myGlobals))
```

There are situations where the above may be awkward (e.g. you want _almost_ all the default globals) so just let me know if that's the case. Would it help if Risor also had options for an allowlist and/or a denylist that were applied? We could do something like:

```go
risor.Eval(ctx, code, risor.WithDenylist("os.exit"))
```

Related question - are you using the `risor.Eval` call, or are you using the lower level parser/compiler/vm APIs?

Certainly you can also make your own cfg.go equivalent, but I'd love to support your exact situation better in the official Risor API, so please share any suggestions on this front. If really needed, I could move Risor's cfg.go out of internal but let's first see if we can add back an API to support what you need in another way.

Thanks, and apologies for this hiccup while I finalize the public APIs!

**Comment by edhemphill** [comment]
Thanks for the detailed response @myzie 

I like the concept of the deny list for certain built-ins. In my case, a requirement would be to not do anything process ending upon a call to a denied function. Ideally simply being able to throw a syntax error or call a custom error handler on that. I think for a lot of embedded use cases that would probably be all that is needed.

I don't see a reason for you to move the cfg out of internal. If someone is using a lot of embedded they will follow your code and build their own config like option as well.  

The plan on our project is to pre-compile the scripts and then call vm.Run on them multiple times (assuming this is possible). I am using risor.go as a guide and just following the risor code to learn all the details.

My guess is any serious user of risor for embedded work would want the flexibility of compiling and then running in separate steps, mostly for performance reasons. Years ago I looked into python for embedded work and found significant issues with its performance for embedded, and ended up using v8 and then a modified node.js in its early years. That then took me too far the other way: It was very complicated to write native code node.js / v8 plugins. And the performance of the v8 runtime would eventually degrade.

My hope is risor can offer good flexibility for embedding (it already has a lot of the basics) but still be relatively simple yet with good performance. Central to that is ability to efficiently call foreign functions. The obvious ones being golang and C. Unfortunately go does not natively support other ABIs (and using cgo would not work here). That's a big miss in my opinion from the go team - but that being said, i recently ran across this:

https://github.com/ebitengine/purego

This potentially could be integrated into risor somehow, which then would let risor code call into DLLs or .so libs. That would be very interesting.

**Comment by myzie** [comment]
Thanks for sharing that context.

As I'm planning the next stages of Risor development, I'm trying to learn more about how folks are using it (or are planning to use it soon). Any chance you'd be able to share a bit more about your project in a conversation on Slack or similar? 

I'm on the gophers.slack.com Slack workspace (as Curtis Myzie). Here's an [invite link](https://join.slack.com/t/gophers/shared_invite/zt-21zsc3q12-55T4LiLzmdZEN~h2IOb~zw) fwiw.

To respond to some of your specific comments there:

> I don't see a reason for you to move the cfg out of internal. If someone is using a lot of embedded they will follow your code and build their own config like option as well.

Sounds good, agreed.

> The plan on our project is to pre-compile the scripts and then call vm.Run on them multiple times (assuming this is possible). I am using risor.go as a guide and just following the risor code to learn all the details.

This is definitely possible, as of the `v0.14.0` release. You'll see that there is a `compiler.Code` type in use now, which is guaranteed safe for reuse across any number of VMs since it is immutable.

> My hope is risor can offer good flexibility for embedding (it already has a lot of the basics) but still be relatively simple yet with good performance

Let me know if anything else is missing re: "flexibility for embedding". For what it's worth, a quick benchmark setup was made [here](https://github.com/risor-io/risor/blob/main/research/bench/Makefile).

I'm open to integrating `purego`. That is interesting. Alternatively, I'm curious if you think a plugin-based approach using different processes might also work in your situation. For example we could use something like [go-plugin](https://github.com/hashicorp/go-plugin) to do lightweight RPC.

**Comment by myzie** [comment]
Oh, I should also mention that another approach is to leverage the virtual OS mechanism. This lets you swap in a different implement of an OS Go interface and the built-ins like `os.exit` will automatically use this interface. 

You could have your own OS implementation that raises an error on `os.exit` instead of the typical behavior.

Or you can use a combination of customized builtins and the OS interface.

**Comment by edhemphill** [comment]
Went the virtual os route...

Am I missing something here? It looks like its not possible to swap out os.exit without an error coming from the runtime:

```
func Exit(ctx context.Context, args ...object.Object) object.Object {
	nArgs := len(args)
	if nArgs > 1 {
		return object.Errorf("type error: exit() expected at most 1 argument (%d given)", nArgs)
	}
	tos := GetOS(ctx)
	if nArgs == 0 {
		tos.Exit(0)
	}
	switch obj := args[0].(type) {
	case *object.Int:
		tos.Exit(int(obj.Value()))
		return object.Errorf("exec error 2: exit(%d)", obj.Value())
	case *object.Error:
		tos.Exit(1)
		return object.Errorf("exec error 1: exit(%s)", obj.Value().Error())
	}
	return object.Errorf("type error: exit() argument must be an int or error (%s given)", args[0].Type())
}
```

In my case I would want to capture the return value the user wished the exit left + keep my executable running (not an error case)...

**Comment by edhemphill** [comment]
I don't think my use case is common enough for you to worry about this.  If I see a way to make it generic enough will let you know. The project's code is very readable and there seems to be plenty of places to tailor it - so good for now.

**Comment by luisdavim** [comment]
@myzie sorry for commenting on a old, closed issue but I'm interested in this use case.

I'd like to have something like:

as well as a way to disable previously added globals:
* `risor.WithDenylist("os.exit")` - disable builtin from module
* `risor.WithoutDefaultGlobal(os)` - disable default builtin / module
* `risor.WithoutGlobal(os)` - disable builtin / module (not sure if this is needed, probably not)

I had a quick look at this part of the code and adding the last 2 would be easy but where would you implement the first one? Would a simple check with `strings.Contains` in `Eval` be good enough? Or maybe in the Parser?

I thought about splitting the strings passed to `WithDenylist` by the `.` and then looking up the module and builtins inside that module but that would be more expensive an more error prone. Any thoughts?

**Comment by luisdavim** [comment]
not sure if something like this would be the best approach https://github.com/risor-io/risor/pull/149 what do you think?

**Comment by myzie** [comment]
> not sure if something like this would be the best approach #149 what do you think?

Hmm. I don't think that the parser update will cut it because someone could work around it.

Taking the `risor.WithDenylist("os.exit")` as an example, someone could write this code to bypass the parser level deny:

```
from os import exit
exit(1)
```

The three approaches that come to mind:
1. Swap in an alternate or no-op implementation of the builtin functions that you want to disable. The alternate implementation could raise an error if called.
2. Have a Risor option that removes a named builtin from a named module, so the builtin isn't there to begin with.
3. Update the VM to disallow calling named builtins based on a deny list at runtime, but this has a runtime cost which would be unfortunate.

The virtual OS approach assists with (1) for the `os` module functions specifically. Maybe a new Risor option is needed to implement the more general form of (1) though. I need to relook at your PR to see if anything you tried was along those lines.

**Comment by phanimahesh** [comment]
Not having fine grained customisability over globals prevents risor from being a serious embedded scripting candidate. Example use case: Allow configurable scripts whose failures are isolated. If a platform allows users to submit scripts to configure certain aspects, I would want to prevent accidentally bad or malicious input from bringing down the whole platform.
Another example usecase: Restrict network calls to allow only http get requests to certain domains, but nothing else.
